# Generated by Django 6.0.3 on 2026-03-13 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_type', models.CharField(choices=[('Teach', 'I can Teach this skill'), ('Learn', 'I want to Learn this skill')], max_length=10)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Design', 'Design'), ('Languages', 'Languages'), ('Music', 'Music'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Photography', 'Photography'), ('Cooking', 'Cooking'), ('Other', 'Other')], max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=20)),
                ('description', models.TextField()),
                ('demo_file', models.FileField(blank=True, null=True, upload_to='skill_demos/')),
                ('availability', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
